-- Eventos adicionales reales de Tequisquiapan, tomados de tequis.travel (fiestas_y_eventos_tequisquiapan/)
-- Fechas exactas cuando la fuente las da; el resto son aproximadas dentro del mes indicado.
-- No se repiten los que ya existían de DataEventSeedData.swift (Feria del Queso y Vino, Festival
-- del Globo, Semana Santa, Fiestas Patrias, Festival de la Cestería, Año Nuevo, Vino Joven, Muertos).

INSERT INTO events (title, short_description, full_description, start_date, end_date, is_recurring, location_name, latitude, longitude, address, category, tags, is_free, thumbnail_url, image_urls, organizer_name)
VALUES
('Fiesta de la Fundación de Tequisquiapan', 'Aniversario de la fundación del pueblo', 'Celebración en el Barrio de la Magdalena con ferias tradicionales, exposiciones comunitarias y desfile de carros alegóricos.', '2026-07-24', '2026-07-24', true, 'Barrio de la Magdalena', 20.5213, -99.8936, 'Barrio de la Magdalena, Tequisquiapan', 'Cívico', ARRAY['Fundación', 'Tradicional', 'Desfile', 'Comunitario'], true, 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('Fiesta de la Santa Cruz', 'Danza de Moros y Cristianos', 'Festividad religiosa en el Barrio de San Juan, con la tradicional Danza de Moros y Cristianos.', '2026-05-03', '2026-05-03', true, 'Barrio de San Juan', 20.5217, -99.8931, 'Barrio de San Juan, Tequisquiapan', 'Religioso', ARRAY['Religioso', 'Danza', 'Tradicional'], true, 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg'], 'Parroquia de Santa María de la Asunción'),

('Fiesta de Santa María de la Asunción', 'Fiesta patronal de Tequisquiapan', 'Festividad patronal principal: misa solemne, danzas, festejos populares y castillo de fuegos artificiales.', '2026-08-15', '2026-08-15', true, 'Parroquia de Santa María de la Asunción', 20.5217, -99.8931, 'Centro Histórico, Tequisquiapan', 'Religioso', ARRAY['Patronal', 'Religioso', 'Fuegos artificiales', 'Danza'], true, 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg'], 'Parroquia de Santa María de la Asunción'),

('Posadas Navideñas', 'Peregrinaciones y villancicos', 'Peregrinación tradicional por las calles del centro con villancicos y ponche, del 16 al 23 de diciembre.', '2026-12-16', '2026-12-23', true, 'Centro Histórico', 20.5213, -99.8936, 'Centro Histórico, Tequisquiapan', 'Tradicional', ARRAY['Navidad', 'Posadas', 'Tradicional', 'Familiar'], true, 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('Enamórate en Tequisquiapan', 'Romance, vino y tradición', 'Programación cultural de febrero con catas de vino, mercado de artesanos locales, talleres y conciertos.', '2027-02-13', '2027-02-15', true, 'Centro Histórico', 20.5213, -99.8936, 'Centro Histórico, Tequisquiapan', 'Gastronomía', ARRAY['Romance', 'Vino', 'Cultural', 'Música'], true, 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Cata_de_quesos_y_vino.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/d/d8/Cata_de_quesos_y_vino.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('Espíritus de Primavera', 'Arte y tradición del equinoccio', 'Celebración del equinoccio de primavera con eventos culturales, performances y mercado de artesanos.', '2027-03-20', '2027-03-21', true, 'Centro Histórico', 20.5213, -99.8936, 'Centro Histórico, Tequisquiapan', 'Cultural', ARRAY['Primavera', 'Equinoccio', 'Arte', 'Cultural'], true, 'https://upload.wikimedia.org/wikipedia/commons/4/42/Artesan%C3%ADas_en_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/4/42/Artesan%C3%ADas_en_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('Festival del Artesano: El Arte de Nuestras Raíces', 'Exhibición de piezas hechas a mano', 'Muestra de artesanías tradicionales en la Plaza Miguel Hidalgo, con piezas hechas a mano por artesanos locales.', '2027-03-06', '2027-03-08', true, 'Plaza Miguel Hidalgo', 20.5213, -99.8936, 'Plaza Miguel Hidalgo, Centro', 'Cultural', ARRAY['Artesanía', 'Cultural', 'Tradicional'], true, 'https://upload.wikimedia.org/wikipedia/commons/4/42/Artesan%C3%ADas_en_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/4/42/Artesan%C3%ADas_en_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('Noches de Leyendas', 'Recorrido teatral de leyendas regionales', 'Actores representan leyendas regionales en un recorrido nocturno que inicia cerca de la parroquia central. Todos los sábados.', '2026-09-12', '2026-09-12', true, 'Parroquia de Santa María de la Asunción', 20.5217, -99.8931, 'Centro Histórico, Tequisquiapan', 'Cultural', ARRAY['Leyendas', 'Teatro', 'Nocturno', 'Cultural'], false, 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/c/cd/Iglesia_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan'),

('La Fiesta del Pueblo', 'La temporada más esperada del año', 'Evento de entrada libre descrito como la temporada más esperada del año en Tequisquiapan.', '2026-08-12', '2026-08-16', false, 'Centro Histórico', 20.5213, -99.8936, 'Centro Histórico, Tequisquiapan', 'Festival', ARRAY['Fiesta', 'Tradicional', 'Familiar'], true, 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg', ARRAY['https://upload.wikimedia.org/wikipedia/commons/a/a6/Plaza_principal_en_Tequisquiapan.jpg'], 'Gobierno Municipal de Tequisquiapan');
