-- Seed de eventos reales de Tequisquiapan para la tabla `events`
-- Corresponde a Tequis Magico/Tequis Magico/DataEventSeedData.swift

INSERT INTO events (title, short_description, full_description, start_date, end_date, is_recurring, location_name, latitude, longitude, address, category, tags, is_free, is_featured, organizer_name, organizer_contact)
VALUES
('Feria Nacional del Queso y Vino', 'El evento más importante del año', 'La Feria Nacional del Queso y Vino es el evento gastronómico más importante de Querétaro. Durante 10-15 días, la plaza principal y calles aledañas se llenan de stands de viñedos, queserías, restaurantes y productores artesanales. Incluye degustaciones, talleres de maridaje, conciertos nocturnos, exposiciones gastronómicas y eventos culturales. No te lo pierdas.', '2026-05-22', '2026-06-07', true, 'Plaza Miguel Hidalgo y Centro Histórico', 20.5213, -99.8936, 'Centro Histórico, Tequisquiapan', 'Feria', ARRAY['Vino', 'Queso', 'Gastronomía', 'Familiar', 'Música', 'Cultural'], true, true, 'Gobierno Municipal de Tequisquiapan', '414-273-0100'),

('Festival del Globo', 'Encuentro de globos aerostáticos', 'Festival anual de globos aerostáticos con participación nacional e internacional. Los globos despegan al amanecer creando un espectáculo visual impresionante. Por la noche, hay shows de glow con los globos iluminados. Incluye actividades familiares, zona de food trucks y música en vivo.', '2027-03-12', '2027-03-14', true, 'Campo de Despegue Principal', 20.5300, -99.8850, 'Campo abierto cerca del centro', 'Festival', ARRAY['Globos', 'Aventura', 'Familia', 'Fotografía', 'Amanecer'], true, true, 'Asociación de Globos Aerostáticos de Querétaro', NULL),

('Semana Santa', 'Procesiones y viacrucis viviente', 'Celebración religiosa tradicional con procesiones diarias, viacrucis viviente representado por la comunidad, misas solemnes y eventos culturales. Las calles del centro se adornan con alfombras de aserrín teñido. Ambiente de recogimiento y tradición.', '2027-04-11', '2027-04-18', true, 'Templos y calles del Centro Histórico', 20.5217, -99.8931, 'Centro Histórico', 'Religioso', ARRAY['Religioso', 'Tradicional', 'Cultural', 'Familiar', 'Histórico'], true, false, 'Parroquia de Santa María de la Asunción', NULL),

('Fiestas Patrias', 'Celebración del grito de independencia', 'Celebración nacional con desfile cívico matutino, eventos culturales durante el día y el tradicional grito de independencia a las 11 PM. Incluye música de mariachi, antojitos mexicanos, fuegos artificiales y decoración tricolor en toda la plaza. Ambiente muy festivo y patriótico.', '2026-09-15', '2026-09-16', true, 'Plaza Miguel Hidalgo', 20.5213, -99.8936, 'Plaza Miguel Hidalgo, Centro', 'Cívico', ARRAY['Patrio', 'Música', 'Fuegos artificiales', 'Familiar', 'Tradicional'], true, true, 'Gobierno Municipal de Tequisquiapan', NULL),

('Festival de la Cestería', 'Celebración del arte de la cestería', 'Festival dedicado a la artesanía tradicional de Tequisquiapan. Talleres gratuitos de cestería, demostraciones de artesanos maestros, concurso de piezas, venta de artesanías y conferencias sobre preservación de técnicas ancestrales. Reconocimiento a artesanos destacados.', '2026-11-08', '2026-11-10', true, 'Casa de la Cultura y Plaza Principal', 20.5216, -99.8927, 'Centro Histórico', 'Cultural', ARRAY['Artesanía', 'Cestería', 'Cultural', 'Talleres', 'Tradicional'], true, false, 'Casa de la Cultura de Tequisquiapan', NULL),

('Año Nuevo en la Plaza', 'Celebración de año nuevo', 'Celebración de fin de año en la plaza principal. Música en vivo, baile, antojitos y bebidas. A las 12 de la noche, brindis colectivo y fuegos artificiales. Ambiente familiar y festivo para recibir el año nuevo.', '2026-12-31 20:00', '2027-01-01 02:00', true, 'Plaza Miguel Hidalgo', 20.5213, -99.8936, 'Plaza Miguel Hidalgo', 'Celebración', ARRAY['Año Nuevo', 'Fiesta', 'Música', 'Fuegos artificiales', 'Brindis'], true, true, 'Gobierno Municipal', NULL),

('Festival del Vino Joven', 'Degustación de vinos nuevos', 'Festival especializado en vinos jóvenes de la cosecha reciente. Los viñedos de la región presentan sus nuevas etiquetas. Incluye catas guiadas por sommeliers, maridajes con quesos locales, conferencias sobre vinicultura y música de jazz en vivo.', '2027-02-20', '2027-02-21', true, 'Viñedos participantes y Plaza Principal', 20.5213, -99.8936, 'Varios lugares', 'Gastronomía', ARRAY['Vino', 'Cata', 'Sommeliers', 'Maridaje', 'Música'], false, false, 'Asociación de Vinicultores de Querétaro', NULL),

('Día de Muertos', 'Celebración tradicional mexicana', 'Celebración del Día de Muertos con tradición mexicana. Concurso de altares en la plaza, ofrendas comunitarias, catrinas vivientes, maquillaje tradicional gratuito, pan de muerto, calaveritas de azúcar. Incluye procesión nocturna al cementerio y eventos culturales.', '2026-11-01', '2026-11-02', true, 'Plaza Miguel Hidalgo y calles del centro', 20.5213, -99.8936, 'Centro Histórico', 'Tradicional', ARRAY['Día de Muertos', 'Altares', 'Catrinas', 'Tradicional', 'Cultural'], true, true, 'Gobierno Municipal y Casa de la Cultura', NULL);

-- Nota: el evento "Festival del Vino Joven" en el Swift original tiene ticket_price/ticket_url/
-- requires_reservation (no gratis); se omiten aquí por simplicidad, ajustar si se necesitan.
UPDATE events SET ticket_price = 'Desde $350', ticket_url = 'https://festivaldelvino.com', requires_reservation = true
WHERE title = 'Festival del Vino Joven';
